=== Eftey/LuoYing/ly-kernel/src/data/object/meta/actor.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fighter.huliqing.name"
           xmlns="http://fighter.huliqing.name"
           elementFormDefault="qualified"
        >
    
    <xs:include schemaLocation="base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="actor" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="actor">
        <xs:annotation>
            <xs:documentation>定义一个角色</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="file" ref="file" use="required"/>
                    <xs:attribute name="icon" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>为角色指定一个图标(64x64), 如：Interface/item/face/female.jpg</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="modules" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation></xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="datas" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation></xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="group" type="xs:integer" use="required">
                        <xs:annotation>
                            <xs:documentation>派系,整数</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="sex" ref="sex" use="required" />
                    <xs:attribute name="race" ref="race" use="required" />
                    <xs:attribute name="level" type="xs:integer" use="required">
                        <xs:annotation>
                            <xs:documentation>设置角色的等级值，等级值将影响角色的：
                                生命、魔法、防御、攻击力等值
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="mass" ref="mass" use="required"/>
                    <xs:attribute name="scale" type="xs:decimal" use="optional"/>
                    <xs:attribute name="mat" ref="mat" use="required" />
                    <xs:attribute name="localForward" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>指定角色原始视角方向,默认情况下为(0,0,1),如果模型默认不是该方向,
                                则需要使用该方向指定模型的正视角方向。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="essential" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                设置角色是否为“必要的”，“必要”是指角色可以死亡，但不能移除出场景。
                                非必要的角色在死亡之后可能被场景的清理器移除出场景,部分比如任务
                                需要的角色不能被移除出场景。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="effects" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                效果列表，格式："effect1,effect2,effect3..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="collisionShape" ref="collisionShape" use="optional" ></xs:attribute>
                    <xs:attribute name="collisionRadius" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>碰撞盒半径,只对capsule类型的collisionShape有效，默认0.4</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="collisionHeight" type="xs:decimal" use="optional">
                        <xs:annotation>
                            <xs:documentation>碰撞盒高度，只对capsule类型的collisionShape有效，默认3.2</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="collisionBoxScale" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>碰撞盒高度的缩放，只对box类型的collisionShape有效，默认"1,1,1",当box类型的
                            碰撞盒太大或者太小时，可使用该参数进行适当缩放</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="drops" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                角色物品的掉落设置，格式： "drop1,drop2,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="hardwareSkinning" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                硬件加速，使用GPU提升skining性能，只有角色拥有skeletonControl时才有意义。
                                默认情况下，该设置会跟随系统的全局设置，但是某些模型可能在使用该功能时
                                存在蒙皮错误，这时候可以使用该选项来关闭该功能。注：只有全局系统打开了
                                hardwareSkinning功能时，该设置才有效。如果全局设置关闭了hardwareSkinning，
                                则即使当前模型打开了该功能也没有用。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="extAnim" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                扩展的骨骼动画包，这个参数指向一个asset中的目录,如：Models/actor/anim
                                当角色使用的技能中找不到相应的动画时将会从这个目录中查找动画文件,注意：
                                动画名称要与文件名一致，比如：动画名称duck_left_roll,则动画文件名为：duck_left_roll.j3o
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="slots" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                定义优先的武器插槽，当角色配备的武器适合这些插槽时，
                                武器将优先绑定在这些插槽上。格式: "slot1,slot2,...".
                                如果没有定义，则以武器自身定义的插槽配置优先。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    
                    <xs:attribute name="lifeAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                指定一个用于定义生命值的属性，格式，如"attributeHealth",该属性可以是已经包含在
                                attributes中的属性也可以不是。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="viewAttribute" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                指定一个哪一个属性为视力属性,如："attributeView"
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="levelUpEl" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                角色的等级升级公式,,必须关联到一条elLevel类型的公式。如果没有设置则角色不会升级。
                                比如一些静态炮塔之类可能就需要配置升级公式。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="xpDropEl" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                角色死亡后的经验掉落公式,必须关联到一条elXpDrop类型的公式，如果没有设置则打死该角色后
                                无法获取经验值奖励。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="team" type="xs:integer" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                角色队伍分组.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="living" type="bool" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                是否为生物,即有生命活动的角色,例如人类,野兽等为生命.
                                非生物如:防御塔,宝箱,祭坛等
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="batch" type="bool" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                batch优化模型，默认false.不可动态设置。只能在xml中初始化配置.
                                打开了batch功能之后角色的装备不可穿和脱.
                                对于一些不需要动态更换装备和武器的角色可以打开该选项进行优化。
                                如：固定装备的NPC。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    
                    <xs:attribute name="logics" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>关联逻辑,多个逻辑使用半角逗号分开，如：logic1,logic2,logic3</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    
                    <xs:attribute name="skills" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                技能列表,半角色逗号分隔
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    
                    <xs:attribute name="skinBase" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                角色的基本皮肤，基本皮肤是用来在切换装备后“修补皮肤”缺失的问题。比如当
                                穿上一套上下连身的法袍（同时包含lowerBody和upperBody）后，再使用一件只
                                包含upperBody的装备来换上时，由于法袍被替换，这时角色身上将丢失lowerBody
                                的装备，这时就需要从skinBase中查看是否有lowerBody的基本皮肤来补上，否则角
                                色会缺少下半身的装备模型。
                                注意：基本皮肤中不要指定哪些包含两个或两个以上type部位的皮肤。比如：
                                同时包含lowerBody和upperBody的skin,如上下连身的套装之类的皮肤，这类皮肤
                                会造成在换装备后进行修补的时候又替换掉已经穿上的装备。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skins" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>指定角色拥有的装备，这些装备是存放在角色包裹上的，格式如: "skin1|total,skin2|total,..."
                                其中total可以省略，默认total=1
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skinOutfit" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>这个参数指定了正在使用中的装备，关联到一件或多件装备,格式如："skinOutfit1,skinOutfit2,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skinWeapon" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>这个参数指定了正在使用中的武器，关联到一件或多件武器，格式如："skinWeapon1,skinWeapon2,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="items" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>角色包裹物品列表，半角逗号分隔,格式如: 
                                itemId1|total,itemId2|total,itemId3</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="resist" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                关联一个抗性设置．
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="channels" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                角色的channel定义,关联一些channel，格式："channel1,channel2,...".
                                如果不设置则默认使用一个包含所有骨骼的channel
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="attributes" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                定义角色的所有属性值,格式如："attribute1,attribute2,attribute3,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="talents" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                角色的天赋，格式: "talent1,talent2,talent3"
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="chat" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                关联到一个Chat
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    
                    <xs:attribute name="talentPoints" type="xs:integer" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                当前角色已有的天赋点数。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="talentPointsLevelEl" type="xs:integer" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                天赋点数的奖励公式，当达到指定等级时可获得的天赋数奖励。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
        
        
    
    
</xs:schema>

=== Eftey/LuoYing/ly-kernel/src/data/object/actor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- play group:0, enemyGroup :1 -->
<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://fighter.huliqing.name'
    xsi:schemaLocation='http://fighter.huliqing.name meta/actor.xsd'>
    
    <!--==========================================================================-->
    <!--Debug test-->
    <!--==========================================================================-->
    
    <!--test-->
    <!-- player test -->    
    <actor id="actorPlayerTest" extends="actorPlayer"
           items="itemMapWorld,item000|100,itemGold|10000,itemTowerSnow|100,itemScrollLife|10
,itemDetoxifyGrass|100,itemTonicRed|5,itemTonicBlue|5,itemHerb|100,itemASTonic|100
,itemTowerStone|100,itemTower|100,itemSpiderSpawn|100
,itemScrollBear|100,itemScrollWolf|100,itemScrollScorpion|100,itemScrollRaptor|100,itemScrollTrex|100
,itemBook005,itemBook006,itemBook007,itemBook008,itemBook010
" 
           talents="talentLifeRestore,talentManaRestore,talentDefence,talentMagicDefence,talentAttack,talentMagicAttack,talentVision,talentMoveSpeed"
           talentPoints="100"
           skins="weaponSword000,weaponSword000L,weaponSword001,weaponSword001L,weaponSword002,weaponSword002L,weaponSword003,weaponSword003L
,weaponBow000,weaponBow001,weaponWand000
,skinHair001,skinHair006,skinHair010,skinHair011,skinBlinder001|12,skinMouthmask001|13,skinHorn001|14
,skinFoot001,skinLowerBody001,skinUpperBody001,skinHand001
,skinFoot002,skinLowerBody002,skinUpperBody002,skinHand002
,skinFoot004,skinLowerBody004,skinUpperBody004,skinHand004
,skinFoot005,skinLowerBody005,skinUpperBody005,skinHand005
,skinFoot006,skinHand006,skinUpperBody006
"
           skinWeapon="weaponSword000,weaponSword000L"
           skills="skillDualSwordWave,skillBowShot,skillIceShot
,skillShotLight,skillShotAddLife,skillShotReborn,skillShotWindWalk,skillShotCleanBuff
,skillDualSwordAttack
,skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillDefend1,skillDefend2
,skillDuckLeft,skillDuckRight,skillDuckBack,skillDuckLeftRoll,skillDuckRightRoll
,skillAttack,skillAttack2,skillAttack3" 
    />
    
    <actor id="actorSinbadTest" extends="actorSinbad" />
    <actor id="actorSkeletonTest" extends="actorPlayer" />
    
    <!--==========================================================================-->
    <!--角色基类-->
    <!--==========================================================================-->
    
    <!--所有角色基类-->
    <actor id="actorBase" channels="channelFull" chat="chatSimple" 
           modules="moduleActor,moduleAction,moduleAttribute,moduleChannel,moduleChat,moduleItem,moduleLogic
    ,moduleResist,moduleSkill,moduleSkin,moduleState,moduleTalent,moduleTask,moduleLevel,moduleDrop"
    />
    
    <!--未分类生物：有生命现象、种族未知、性别未知的角色, 如: 未分类人物、动物、野兽、怪物等 -->
    <actor id="actorLiveBase" extends="actorBase" attributes="attributeActorLiving"
           modules="moduleActor,moduleAction,moduleAttribute,moduleChannel,moduleChat,moduleItem,moduleLogic
    ,moduleResist,moduleSkill,moduleSkin,moduleState,moduleTalent,moduleTask,moduleLevel,moduleDrop"
           logics="logicSearchEnemy,logicDynamicFight,logicPatrol,logicFollow,logicDefend"
           />
    
    <!--未分类静物：无生命迹象、种族未知、性别未知的角色， 如: 炮塔、宝箱、祭坛、房屋等-->
    <actor id="actorNonLiveBase" extends="actorBase" attributes="attributeActorUnliving"
           modules="moduleActor,moduleAction,moduleAttribute,moduleChannel,moduleChat,moduleItem,moduleLogic
    ,moduleResist,moduleSkill,moduleSkin,moduleState,moduleTask,moduleLevel,moduleDrop"
           logics="logicSearchEnemy,logicStaticFight"
           resist="resistNonLife"
           />

    <!--种族配置： 人类女性-->
    <actor id="actorHumanFemaleBase" extends="actorBase" attributes="attributeHumanFemale"
            modules="moduleActor,moduleAction,moduleAttribute,moduleChannel,moduleChat,moduleItem,moduleLogic
    ,moduleResist,moduleSkill,moduleSkin,moduleState,moduleTalent,moduleTask,moduleLevel,moduleDrop"
            logics="logicSearchEnemy,logicDynamicFight,logicPatrol,logicFollow,logicDefend"
            channels="channelLowerBody,channelUpperBody,channelLeftHand,channelRightHand,channelHead"
            resist="resistHuman"
            file="Models/actor/ske.mesh.j3o"
            icon="Interface/face/female1.jpg"
            extAnim="Models/actor/ext_anim" 
            skinBase="skinEar000,skinEye000,skinFace000,skinFoot000,skinHair010,skinHand000,skinLowerBody000,skinUpperBody000"
            skins="skinLowerBody002|1,weaponSword000"
            skinOutfit="skinFoot003,skinHand003,skinLowerBody003,skinUpperBody003"
            skinWeapon="weaponSword000"
            skills="skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillDefend1,skillDefend2
,skillDuckLeft,skillDuckRight,skillDuckBack,skillDuckLeftRoll,skillDuckRightRoll
,skillAttack,skillAttack2,skillAttack3
,skillBowShot
,skillDualSwordAttack"

            scale="0.2" mass="60" group="1" mat="4"
           />
           
    <!--种族配置： 人类男性（暂无）-->
    <!--种族配置： 兽人女性（暂无）-->
    <!--种族配置： 兽人男性（暂无）-->
    
    <!--==========================================================================-->
    <!--种族类角色配置: 人类-女性-->
    <!--==========================================================================-->
    
<!--    人类种族、女性基本配置
    <actor id="actorHumanFemaleBase" extends="actorLiveBase" file="Models/actor/ske.mesh.j3o" sex="0" race="1"
            icon="Interface/face/female1.jpg"
            scale="0.2" mass="60" group="1" mat="4" level="1" resist="resistHuman"
            channels="channelLowerBody,channelUpperBody,channelLeftHand,channelRightHand,channelHead"
            extAnim="Models/actor/ext_anim" 
            skinBase="skinEar000,skinEye000,skinFace000,skinFoot000,skinHair010,skinHand000,skinLowerBody000,skinUpperBody000"
            skins="skinLowerBody002|1,weaponSword000"
            skinOutfit="skinFoot003,skinHand003,skinLowerBody003,skinUpperBody003"
            skinWeapon="weaponSword000" 
            slots="slotSwordLeftBack,slotSwordLeftBack2,slotSwordLeftWaist,slotSwordLeftWaist2,slotBowLeftBack,slotWandLeftBack"
            items="itemTonicRed|5,itemTonicBlue|5,itemSpiderSpawn|1,itemTower|1" 
            skills="skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillDefend1,skillDefend2
,skillDuckLeft,skillDuckRight,skillDuckBack,skillDuckLeftRoll,skillDuckRightRoll
,skillAttack,skillAttack2,skillAttack3
,skillBowShot
,skillDualSwordAttack"
            />-->
    
    <!-- player-->
    <actor id="actorPlayer" extends="actorHumanFemaleBase" skinWeapon="weaponBow000" 
           logics="logicSearchEnemyForPlayer,logicPlayer" 
           talents="talentLifeRestore,talentDefence,talentAttack"
           items="itemTonicRed|5,itemTonicBlue|5,itemSpiderSpawn|1,itemTower|1" 
    />
    
    
    <!--战士-->
    <actor id="actorWarrior" extends="actorHumanFemaleBase" icon="Interface/face/female1.jpg"
           logics="logicSearchEnemyForPlayer,logicPlayer"
           talents="talentLifeRestore,talentDefence,talentAttack"
           skinOutfit="skinFoot005,skinHand005,skinLowerBody005,skinUpperBody005"
           items="itemTonicRed|10,itemTonicBlue|5,itemTower|1" 
           skins="weaponSword002L"
           skinWeapon="weaponSword001" 
           skills="skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillAttack,skillAttack2,skillAttack3,skillDualSwordAttack,skillBowShot
,skillDanceSakura,skillDualSwordWave
,skillDefend1,skillDefend2
,skillDuckLeft,skillDuckRight,skillDuckBack,skillDuckLeftRoll,skillDuckRightRoll
" />
    
    <!--牧师-->
    <actor id="actorPastor" extends="actorHumanFemaleBase" icon="Interface/face/female2.jpg"
           logics="logicSearchEnemyForPlayer,logicPlayer"
           talents="talentManaRestore,talentMagicDefence,talentMagicAttack"
           items="itemTonicRed|5,itemTonicBlue|10" 
           skinBase="skinEar000,skinEye000,skinFace000,skinFoot000,skinHair006,skinHand000,skinLowerBody000,skinUpperBody000"
           skinOutfit="skinFoot006,skinHand006,skinUpperBody006"
           skinWeapon="weaponWand000" 
           skills="skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillAttack,skillAttack2,skillAttack3,skillDualSwordAttack,skillBowShot
,skillShotLight,skillShotAddLife,skillShotReborn,skillShotWindWalk,skillShotCleanBuff
" />
    
    <!--猎人-->
    <actor id="actorHunter" extends="actorHumanFemaleBase" icon="Interface/face/female3.jpg"
           logics="logicSearchEnemyForPlayer,logicPlayer"
           talents="talentAttack,talentDefence,talentVision,talentMoveSpeed"
           items="itemTonicRed|10,itemTonicBlue|5,itemHerb|5,itemTowerStone|1" 
           skinBase="skinEar000,skinEye000,skinFace000,skinFoot000,skinHair011,skinHand000,skinLowerBody000,skinUpperBody000"
           skins="weaponSword000"
           skinOutfit="skinFoot003,skinHand003,skinUpperBody003,skinLowerBody003,skinMouthmask001"
           skinWeapon="weaponBow001" 
           skills="skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillAttack,skillAttack2,skillAttack3,skillDualSwordAttack,skillBowShot
,skillSummon,skillLightningShot,skillIceShot
" />
    
    <!-- hard -->
    <actor id="actorHard" extends="actorHumanFemaleBase"  
           skinOutfit="skinFoot001,skinHand001,skinLowerBody001,skinUpperBody001,skinHair006"
           skills="skillWait,skillWalk,skillRun,skillReset,skillDead,skillHurtFront,skillHurtBack
,skillDefend1,skillDefend2
,skillDuckLeft,skillDuckRight,skillDuckBack,skillDuckLeftRoll,skillDuckRightRoll
,skillAttack,skillAttack2,skillAttack3
,skillBowShot
,skillDualSwordAttack
,skillDanceSakura,skillLightningShot
"
    />
