=== Eftey/LuoYing/ly-kernel/src/data/object/meta/drop.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fighter.huliqing.name"
           xmlns="http://fighter.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="drop" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="drop">
        <xs:annotation>
            <xs:documentation>掉落物品设置，
                注意：所有允许掉落的物品必须是来自obj、weapon、skin中定义的物品,
                使用其它物品ID可能会有不可预料的错误。
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="base" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>基本的物品掉落ID，格式如“id1|count,id2,id3”，
                                这些物品是必定掉落的，不会受任何其它百分比影响,第二个参数表示掉落的数量，
                                如果不提供，则默认1.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="random" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>随机掉落的物品列表，示例：
                                "id1|count|factor, id2|count|factor, id3|count|factor"
                                1.count为掉落数量,如果该值省略，则默认1
                                2.factor表示掉落率，取值从[0.0~1.0],该参数还受
                                系统全局设置的影响。比如：factor=0.5, 而全局掉落设置为0.5,
                                则最终该物品掉落的机率为0.25,如果该值不省略，则默认1.
                                3.factor和count可省略，默认count=1, factor=1.0
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    
</xs:schema>

=== Eftey/LuoYing/ly-core/src/data/object/drop.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--定义角色的可掉落物-->

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://fighter.huliqing.name'
    xsi:schemaLocation='http://fighter.huliqing.name meta/drop.xsd'>

    <!--=====================================================================-->
    <!-- 基本配置 -->
    <!--=====================================================================-->
    
    <!--什么也不掉: 用于游戏中动态设置-->
    <drop id="dropEmpty" />
    
    <!--=====================================================================-->
    <!-- 特殊配置 -->
    <!--=====================================================================-->
    
    <!--丛林蜘蛛掉落设置-->
    <drop id="dropSpider" random="itemGold|20,itemTonicRed|2|0.2,itemTonicBlue|2|0.2,itemSpiderSpawn|1|0.15,itemHerb|1|0.2" />
    
    <!--丛林盗贼-->
    <drop id="dropNinja" random="itemGold|20,itemTonicRed|2|0.2,itemTonicBlue|2|0.2,itemTower|1|0.15,itemTowerStone|1|0.15,itemTowerSnow|1|0.15" />
    
    <!--狼-->
    <drop id="dropWolf" random="itemGold|10,itemTonicRed|2|0.2,itemTonicBlue|2|0.2,itemScrollWolf|1|0.3" />
    
    <!--熊-->
    <drop id="dropBear" random="itemGold|10,itemTonicRed|2|0.2,itemTonicBlue|2|0.2,itemScrollBear|1|0.3" />
    
    <!--蝎子-->
    <drop id="dropScorpion" random="itemGold|10,itemTonicRed|2|0.2,itemTonicBlue|2|0.2,itemScrollScorpion|1|0.3,itemDetoxifyGrass|1|0.2" />
    
    <!--古柏幼仔-->
    <drop id="dropGb" random="itemGold|20,itemTonicRed|1|0.2,itemTonicBlue|1|0.2,itemHerb|1|0.1" />

    <!--山老大－辛巴达-->
    <drop id="dropSinbad" random="itemGold|20,itemTonicRed|2|0.3,itemTonicBlue|2|0.3,itemTower|1|0.3,itemTowerStone|1|0.3,itemTowerSnow|1|0.2,itemHerb|1|0.3,itemASTonic|1|0.05" />
    
    <!--森林妖精-->
    <drop id="dropFairy" base="itemBook008" random="itemGold|20,skinFoot004|1|0.5,skinHand004|1|0.5,skinLowerBody004|1|0.5,skinUpperBody004|1|0.5,itemHerb|1|1,itemASTonic|1|0.05" />

    <!--trex-->
    <drop id="dropTrex" random="itemGold|100,itemTonicRed|5|0.3,itemTonicBlue|5|0.3,itemHerb|1|0.2,itemASTonic|1|0.1" />

    <!--raptor-->
    <drop id="dropRaptor" random="itemGold|40,itemTonicRed|2|0.3,itemTonicBlue|2|0.3,itemHerb|1|0.2,itemASTonic|1|0.05" />


</root>
