=== Eftey/LuoYing/ly-kernel/src/data/object/meta/module.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fighter.huliqing.name"
           xmlns="http://fighter.huliqing.name"
           elementFormDefault="qualified"
        >
    
    <xs:include schemaLocation="base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="moduleAction" />
                <xs:element ref="moduleAttribute" />
                <xs:element ref="moduleBase" />
                <xs:element ref="moduleChannel" />
                <xs:element ref="moduleChat" />
                <xs:element ref="moduleItem" />
                <xs:element ref="moduleLogic" />
                <xs:element ref="modulePhysics" />
                <xs:element ref="moduleResist" />
                <xs:element ref="moduleSkill" />
                <xs:element ref="moduleSkin" />
                <xs:element ref="moduleState" />
                <xs:element ref="moduleTalent" />
                <xs:element ref="moduleTask" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="moduleTask">
        <xs:annotation>
            <xs:documentation>角色任务模块</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="moduleTalent">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleState">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
        
    <xs:element name="moduleSkin">
        <xs:annotation>
            <xs:documentation>角色装备控制器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleSkill">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleResist">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="modulePhysics">
        <xs:annotation>
            <xs:documentation>角色物理控制器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="radius" type="xs:decimal" use="required" />
                    <xs:attribute name="height" type="xs:decimal" use="required" />
                    <xs:attribute name="mass" type="xs:decimal" use="required" />
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleLogic">
        <xs:annotation>
            <xs:documentation>角色逻辑控制器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="logics" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>关联逻辑,多个逻辑使用半角逗号分开，如：logic1,logic2,logic3</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleItem">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleChat">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleChannel">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="channels" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                角色的channel定义,关联一些channel，格式："channel1,channel2,...".
                                如果不设置则默认使用一个包含所有骨骼的channel
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
        
    <xs:element name="moduleBase">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleAttribute">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="moduleAction">
        <xs:annotation>
            <xs:documentation>xxxx</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== Eftey/LuoYing/ly-kernel/src/data/object/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- play group:0, enemyGroup :1 -->
<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://fighter.huliqing.name'
    xsi:schemaLocation='http://fighter.huliqing.name meta/module.xsd'>
    
    
    <moduleActor id="moduleActor" />
    <moduleAction id="moduleAction" />
    <moduleAttribute id="moduleAttribute"/>
    <moduleChannel id="moduleChannel"/>
    <moduleChat id="moduleChat"/>
    <moduleItem id="moduleItem"/>
    <moduleLogic id="moduleLogic"/>
    <modulePhysics id="modulePhysics" />
    <moduleResist id="moduleResist" />
    <moduleSkill id="moduleSkill"/>
    <moduleSkin id="moduleSkin"/>
    <moduleState id="moduleState"/>
    <moduleTalent id="moduleTalent"/>
    <moduleTask id="moduleTask"/>
        

</root>
