=== Eftey/LuoYing/ly-kernel/src/data/object/meta/skin.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fighter.huliqing.name"
           xmlns="http://fighter.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="skinOutfit" />
                <xs:element ref="skinWeapon" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="skinWeapon">
        <xs:annotation>
            <xs:documentation>
                武器装备
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="baseSkin">
                    <xs:attribute name="weaponType" ref="weaponType" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                指定一个武器类型，只有设置了该值，该skin才能作为武器类型存在,否则只作为普通装备。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="slots" type="xs:integer" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                设置武器支持的槽位列表,格式如："slot1,slot2,...",
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="skinOutfit">
        <xs:annotation>
            <xs:documentation>
                基本skin,如：皮肤，装备等
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="baseSkin">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="baseSkin">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="icon" ref="icon" use="required" />
                <xs:attribute name="file" ref="file" use="required" />
                <xs:attribute name="baseSkin" type="bool" use="optional" >
                    <xs:annotation>
                        <xs:documentation>是否为基本破肤</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="type" use="required" >
                    <xs:annotation>
                        <xs:documentation>
                            skin的类型，格式如："type1,type2,type3",注：即一个skin可以属于多个type的。
                            比如上下连身的长袍的type可能为"7,8", 目前最多支持32个类型，取值从[0-31],
                            不要超过该范围
                            type参考如下（具体以SkinConstants所定义的type为准）：
                            ear(1), eye(2), face(3), foot(4), hair(5), hand(6), lowerBody(7), upperBody(8);
                            weaponLeft左武器(9),weaponRight右武器(10),
                            blinder眼罩(11),mouthMask口罩(12),faceMask面罩(13),horn角(14),
                        </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string" >
                            <xs:enumeration value="1" />
                            <xs:enumeration value="2" />
                            <xs:enumeration value="3" />
                            <xs:enumeration value="4" />
                            <xs:enumeration value="5" />
                            <xs:enumeration value="6" />
                            <xs:enumeration value="7" />
                            <xs:enumeration value="8" />
                            <xs:enumeration value="9" />
                            <xs:enumeration value="10" />
                            <xs:enumeration value="11" />
                            <xs:enumeration value="12" />
                            <xs:enumeration value="13" />
                            <xs:enumeration value="14" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="conflictType" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            排斥的目标skin类型，格式："type1,type2,type3,...",一般情况下，当一个skin添加到角色身上时，目标角色身上的
                            相同类型(type)的skin会脱下来收起，即同一个类型的skin不可能同时添加到角色身上.而conflictType参数可指定其它
                            类型的skin也脱下来，比如当面具带上去时，这时眼罩和口罩可能要从角色身上脱下。则对面具类型的conflictType参数可
                            设定为:"11,12"
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="bindBone" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                            如果指定了一个骨头名称，则skin将会被绑定到该骨头上,否则将直接被绑定到目标根节点。
                            注：对于使用bindBone的skin模型必须在blender导出时使用obj格式，不能使用ogre格式导出。
                            否则在绑定到角色身上时会发生错位。对于静态类的skin模型（即没有动画、不受权重影响的模型）
                            直接绑定到骨头节点上性能比较好。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="localLocation" type="xs:stirng" use="optional">
                    <xs:annotation><xs:documentation>skin添加到目标时的本地变换，格式："x,y,z"</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="localRotation" type="xs:stirng" use="optional">
                    <xs:annotation><xs:documentation>skin添加到目标时的本地旋转(弧度)，格式："x,y,z"</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="localScale" type="xs:stirng" use="optional">
                    <xs:annotation><xs:documentation>skin添加到目标时的本地缩放，格式："x,y,z"</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="applyAttributes" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                            指定要应用到目标角色上的属性，格式："attribute|value",多个设置使用半角逗号分隔。
                            示例："attributeDefence|50,attributeMagicDefence|30", 表示物理防御+50，魔法防御+30
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="matchAttributes" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                            属性限制，这些限制定义了：只有角色的属性与这些限制完全匹配时才可以使用这件物品
                            格式："attributeName|value,attributeName|value,..."
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="mat" ref="mat" use="required" />
                <xs:attribute name="cost" ref="cost" use="optional" />
                <xs:attribute name="sounds" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>声效,格式:"sound1,sound2,..."</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== Eftey/LuoYing/ly-core/src/data/object/skin_weapon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
skinType => 0:body; 1:armor 
skinPart => 0:ear;1:eyeL;2:eyeR;3:face;4:foot;5:hair;6:hand;7:lowerBody;8:upperBody; 
-->

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://fighter.huliqing.name'
    xsi:schemaLocation='http://fighter.huliqing.name meta/skin.xsd'>
    
    <!--=====================================================================-->
    <!--虚拟的武器，无实物模型,用于所有无实际武器的角色。-->
    <!--=====================================================================-->
    
    <!--虚拟一把右手剑-->
    <skinWeapon id="weaponMockRightSword" type="10" mat="1" weaponType="1" handler="handlerWeaponSword" />
    <!--虚拟一柄木剑-->
    <skinWeapon id="weaponMockRightWoodSword" type="10" mat="2" weaponType="1" handler="handlerWeaponSword" />
    <!--虚拟一双动物爪子-->
    <skinWeapon id="weaponMockAnimalClaw" type="9,10" mat="5" weaponType="4" handler="handlerWeaponSword" />
    
    <!-- ====================================================================-->
    <!--基本配置定义-->
    <!-- ====================================================================-->
    
    <!--右手剑-->
    <skinWeapon id="weaponRightSwordBase" type="10" weaponType="1" mat="1" 
                handler="handlerWeaponSword" raceLimit="1" bindBone="weapon.R" 
                localTranslation="0,0,0" localRotation="0,0,0" 
                slots="slotSwordLeftBack,slotSwordLeftBack2,slotSwordRightBack,slotSwordRightBack2,slotSwordLeftWaist,slotSwordLeftWaist2" />
    
    <!--左手剑-->
    <skinWeapon id="weaponLeftSwordBase" extends="weaponRightSwordBase" type="9" 
                bindBone="weapon.L" localRotation="0,3.14159265,0" localTranslation="0,0,0" />

    <!--弓-->
    <skinWeapon id="weaponBowBase" type="9" conflictType="10" bindBone="weapon.L" localRotation="0,0,0" localTranslation="0,0,0"
                mat="2" handler="handlerWeaponBow" weaponType="3" raceLimit="1" slots="slotBowLeftBack" />

    <!--魔杖-->
    <skinWeapon id="weaponWandBase" type="10" conflictType="9" bindBone="weapon.R" localRotation="0,0,0" localTranslation="0,0,0"
                mat="2" handler="handlerWeaponWand" weaponType="6" raceLimit="1" slots="slotWandLeftBack" />
    
    <!--魔法书：暂未开放-->
    <skinWeapon id="weaponBookBase" type="9" conflictType="10" bindBone="weapon.L" mat="0" localRotation="0,0,0" localTranslation="0,0,0"
                handler="" weaponType="5" />
    
    <!-- ====================================================================-->
    <!--实质武器:刀，剑-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponSword000"  extends="weaponRightSwordBase" cost="0"
                icon="Models/weapon/sword/sword000.png" file="Models/weapon/sword/sword000.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|5" />
    <skinWeapon id="weaponSword000L" extends="weaponLeftSwordBase" cost="0"
                icon="Models/weapon/sword/sword000.png" file="Models/weapon/sword/sword000.j3o"
                applyAttributes="attributeAttack|5,attributeMagicAttack|2" />
    
    <skinWeapon id="weaponSword001"  extends="weaponRightSwordBase" cost="1200"
                icon="Models/weapon/sword/sword001.png" file="Models/weapon/sword/sword001.j3o"
                applyAttributes="attributeAttack|15,attributeMagicAttack|7" />
    <skinWeapon id="weaponSword001L" extends="weaponLeftSwordBase" cost="1200"
                icon="Models/weapon/sword/sword001.png" file="Models/weapon/sword/sword001.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|5" />
    
    <skinWeapon id="weaponSword002"  extends="weaponRightSwordBase" cost="1400"
                icon="Models/weapon/sword/sword002.png" file="Models/weapon/sword/sword002.j3o" 
                applyAttributes="attributeAttack|20,attributeMagicAttack|8" />
    <skinWeapon id="weaponSword002L" extends="weaponLeftSwordBase" cost="1400"
                icon="Models/weapon/sword/sword002.png" file="Models/weapon/sword/sword002.j3o"
                applyAttributes="attributeAttack|15,attributeMagicAttack|6" />
    
    <skinWeapon id="weaponSword003"  extends="weaponRightSwordBase" cost="1600"
                icon="Models/weapon/sword/sword003.png" file="Models/weapon/sword/sword003.j3o" 
                applyAttributes="attributeAttack|25,attributeMagicAttack|10" />
    <skinWeapon id="weaponSword003L" extends="weaponLeftSwordBase" cost="1600"
                icon="Models/weapon/sword/sword003.png" file="Models/weapon/sword/sword003.j3o"
                applyAttributes="attributeAttack|20,attributeMagicAttack|8" />
    
    <!-- ====================================================================-->
    <!--实质武器:弓-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponBow000" extends="weaponBowBase" cost="0"
                icon="Models/weapon/bow/bow000.mesh.png" file="Models/weapon/bow/bow000.mesh.j3o" 
                applyAttributes="attributeAttack|30" />
    
    <skinWeapon id="weaponBow001" extends="weaponBowBase" cost="1600"
                icon="Models/weapon/bow/bow001.mesh.png" file="Models/weapon/bow/bow001.mesh.j3o"
                applyAttributes="attributeAttack|40" />
    
    <!-- ====================================================================-->
    <!--实质武器:魔杖-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponWand000" extends="weaponWandBase" cost="1200"
                icon="Models/weapon/wand/wand000.png" file="Models/weapon/wand/wand000.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|50,attributeMana|100" />
    
    <!-- ====================================================================-->
    <!--实质武器:魔法书-->
    <!-- ====================================================================-->
    <skinWeapon id="weaponBook000" extends="weaponBookBase" cost="1200"
                icon="Models/weapon/book/book000.mesh.png" file="Models/weapon/book/book000.mesh.j3o" 
                applyAttributes="attributeAttack|5,attributeMagicAttack|40,attributeMana|100" />
    
    
    <!-- ====================================================================-->
    <!--特殊角色的武器-->
    <!-- ====================================================================-->
    
    <!--Sinbad的大刀-->
    <skinWeapon id="weaponSinbad" icon="" file="Models/monster/sinbad/Sword.j3o" 
                type="10" bindBone="weapon.R" mat="1" handler="handlerWeaponSword" weaponType="1" raceLimit="2" sexLimit="1"
                applyAttributes="attributeAttack|25" />

</root>

=== Eftey/LuoYing/ly-kernel/src/data/object/skin_weapon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
skinType => 0:body; 1:armor 
skinPart => 0:ear;1:eyeL;2:eyeR;3:face;4:foot;5:hair;6:hand;7:lowerBody;8:upperBody; 
-->

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://fighter.huliqing.name'
    xsi:schemaLocation='http://fighter.huliqing.name meta/skin.xsd'>
    
    <!-- =========================================================================-->
    <!--基本定义-->
    <!-- =========================================================================-->
    
    <!--人类武器装备-->
    <skinOutfit id="weaponHumanBase" matchAttributes="attributeRace|1" />
    
    <!-- =========================================================================-->
    <!--人类武器分类定义-->
    <!-- =========================================================================-->
    
    <!--右手剑-->
    <skinWeapon id="weaponHumanRightSwordBase" extends="weaponHumanBase" type="10" weaponType="1" mat="1" 
                bindBone="weapon.R" localLocation="0,0,0" localRotation="0,0,0" sounds="soundDrawSword" 
                slots="slotSwordLeftBack,slotSwordLeftBack2,slotSwordRightBack,slotSwordRightBack2,slotSwordLeftWaist,slotSwordLeftWaist2" />
    
    <!--左手剑-->
    <skinWeapon id="weaponHumanLeftSwordBase" extends="weaponHumanRightSwordBase" type="9" 
                bindBone="weapon.L" localRotation="0,3.14159265,0" localLocation="0,0,0" />

    <!--弓-->
    <skinWeapon id="weaponHumanBowBase" extends="weaponHumanBase" type="9" conflictType="10" bindBone="weapon.L" localRotation="0,0,0" localLocation="0,0,0"
                mat="2"  weaponType="3"  slots="slotBowLeftBack" sounds="soundDrawBow" />

    <!--魔杖-->
    <skinWeapon id="weaponHumanWandBase" extends="weaponHumanBase" type="10" conflictType="9" bindBone="weapon.R" localRotation="0,0,0" localLocation="0,0,0"
                mat="2" weaponType="6"  slots="slotWandLeftBack" sounds="soundDressOutfit2" />
    
    <!--魔法书：暂未开放-->
    <skinWeapon id="weaponHumanBookBase" extends="weaponHumanBase" type="9" conflictType="10" bindBone="weapon.L" mat="0" localRotation="0,0,0" localLocation="0,0,0"
                weaponType="5" sounds="" />
    
    <!--=====================================================================-->
    <!--虚拟的武器，无实物模型,用于所有无实际武器的角色。-->
    <!--=====================================================================-->
    
    <!--虚拟一把右手剑-->
    <skinWeapon id="weaponMockRightSword" type="10" mat="1" weaponType="1" sounds="soundDrawSword" />
    <!--虚拟一柄木剑-->
    <skinWeapon id="weaponMockRightWoodSword" type="10" mat="2" weaponType="1" sounds="soundDrawSword" />
    <!--虚拟一双动物爪子-->
    <skinWeapon id="weaponMockAnimalClaw" type="9,10" mat="5" weaponType="4" sounds="soundDrawSword" />
    
    <!-- ====================================================================-->
    <!--实质武器:刀，剑-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponSword000"  extends="weaponHumanRightSwordBase" cost="0"
                icon="Models/weapon/sword/sword000.png" file="Models/weapon/sword/sword000.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|5" />
    <skinWeapon id="weaponSword000L" extends="weaponHumanLeftSwordBase" cost="0"
                icon="Models/weapon/sword/sword000.png" file="Models/weapon/sword/sword000.j3o"
                applyAttributes="attributeAttack|5,attributeMagicAttack|2" />
    
    <skinWeapon id="weaponSword001"  extends="weaponHumanRightSwordBase" cost="1200"
                icon="Models/weapon/sword/sword001.png" file="Models/weapon/sword/sword001.j3o"
                applyAttributes="attributeAttack|15,attributeMagicAttack|7" />
    <skinWeapon id="weaponSword001L" extends="weaponHumanLeftSwordBase" cost="1200"
                icon="Models/weapon/sword/sword001.png" file="Models/weapon/sword/sword001.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|5" />
    
    <skinWeapon id="weaponSword002"  extends="weaponHumanRightSwordBase" cost="1400"
                icon="Models/weapon/sword/sword002.png" file="Models/weapon/sword/sword002.j3o" 
                applyAttributes="attributeAttack|20,attributeMagicAttack|8" />
    <skinWeapon id="weaponSword002L" extends="weaponHumanLeftSwordBase" cost="1400"
                icon="Models/weapon/sword/sword002.png" file="Models/weapon/sword/sword002.j3o"
                applyAttributes="attributeAttack|15,attributeMagicAttack|6" />
    
    <skinWeapon id="weaponSword003"  extends="weaponHumanRightSwordBase" cost="1600"
                icon="Models/weapon/sword/sword003.png" file="Models/weapon/sword/sword003.j3o" 
                applyAttributes="attributeAttack|25,attributeMagicAttack|10" />
    <skinWeapon id="weaponSword003L" extends="weaponHumanLeftSwordBase" cost="1600"
                icon="Models/weapon/sword/sword003.png" file="Models/weapon/sword/sword003.j3o"
                applyAttributes="attributeAttack|20,attributeMagicAttack|8" />
    
    <!-- ====================================================================-->
    <!--实质武器:弓-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponBow000" extends="weaponHumanBowBase" cost="0"
                icon="Models/weapon/bow/bow000.mesh.png" file="Models/weapon/bow/bow000.mesh.j3o" 
                applyAttributes="attributeAttack|30" />
    
    <skinWeapon id="weaponBow001" extends="weaponHumanBowBase" cost="1600"
                icon="Models/weapon/bow/bow001.mesh.png" file="Models/weapon/bow/bow001.mesh.j3o"
                applyAttributes="attributeAttack|40" />
    
    <!-- ====================================================================-->
    <!--实质武器:魔杖-->
    <!-- ====================================================================-->
    
    <skinWeapon id="weaponWand000" extends="weaponHumanWandBase" cost="1200"
                icon="Models/weapon/wand/wand000.png" file="Models/weapon/wand/wand000.j3o" 
                applyAttributes="attributeAttack|10,attributeMagicAttack|50,attributeMana|100" />
    
    <!-- ====================================================================-->
    <!--实质武器:魔法书-->
    <!-- ====================================================================-->
    <skinWeapon id="weaponBook000" extends="weaponHumanBookBase" cost="1200"
                icon="Models/weapon/book/book000.mesh.png" file="Models/weapon/book/book000.mesh.j3o" 
                applyAttributes="attributeAttack|5,attributeMagicAttack|40,attributeMana|100" />
    
    <!-- ====================================================================-->
    <!--特殊角色的武器-->
    <!-- ====================================================================-->
    
    <!--Sinbad的大刀-->
    <skinWeapon id="weaponSinbad" icon="" file="Models/monster/sinbad/Sword.j3o" 
                type="10" bindBone="weapon.R" mat="1" sounds="soundDrawSword" weaponType="1"
                applyAttributes="attributeAttack|25" />

</root>
