=== Eftey/LuoYing/ly-kernel/src/data/object/meta/state.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fighter.huliqing.name"
           xmlns="http://fighter.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <!--改变属性-->
                <xs:element ref="stateAttribute" />

                <!--移动速度-->
                <xs:element ref="stateAttributeMove" />
                
                <!--可持续改变角色属性动态值的状态-->
                <xs:element ref="stateAttributeDynamic" />

                <!--技能锁定-->
                <xs:element ref="stateSkillLocked" />
                
                <!--不可或缺的，死亡后不会移出场景-->
                <xs:element ref="stateEssential" />
                
                <!--执行技能-->
                <xs:element ref="stateSkill" />

                <!--状态清除-->
                <xs:element ref="stateClean" />

                <!--状态组-->
                <xs:element ref="stateGroup" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateGroup">
        <xs:annotation>
            <xs:documentation>
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateBase">
                    <xs:attribute name="states" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>状态组，格式："stateId,stateId,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateClean">
        <xs:annotation>
            <xs:documentation>
                这类状态可以用来清除角色身上的一些其它状态,当状态在运行时会不停的检查角色当前的状态
                列表，并偿试清除指定的状态，甚至清除自身状态。可用用来作为一些净化类的技能使用。
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateBase">
                    <xs:attribute name="states" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定要清除的状态列表，格式:"stateId,stateId,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateSkill">
        <xs:annotation>
            <xs:documentation>执行一个技能</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateBase">
                    <xs:attribute name="skillType" use="required">
                        <xs:annotation>
                            <xs:documentation>指定要执行的是哪一个类型的技能，如果角色不存在该类型的技能则什么也不做。</xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="wait" />
                                <xs:enumeration value="reset"  />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="force" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>是否强制执行技能</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateSkillLocked">
        <xs:annotation>
            <xs:documentation>锁定角色的技能</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateBase">
                    <xs:attribute name="lockAll" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                强制锁定所有技能,如果该值设置为true,
                                则忽略参数:lockSkillTypes、lockSkillIds、lockChannels的设置。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="lockSkillTypes" type="skillType" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                指定要锁定的特定的技能类型列表,可以设置多个，使用半角逗号分隔，
                                如："wait,sit,run,..."， 注：如果参数 lockAll=true,则忽略lockSkills设置
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="lockSkillIds" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                指定要锁定的特定技能的id列表,如果角色没有指定id的技能则不会有任何影响,
                                格式："skillId1,skillId2,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="lockChannels" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                指定要锁定的角色动画通道列表,如果指定的角色没有相应的动画通道则什么也不处理
                                ,格式："channel1,channel2,..."
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="lockType" use="optional">
                        <xs:annotation>
                            <xs:documentation>reset表示锁定在ResetSkill上，frame表示锁定在当前动画帧上</xs:documentation>
                        </xs:annotation>
                        <xs:simpleType>
                            <xs:restriction base="xs:string" >
                                <xs:enumeration value="reset" />
                                <xs:enumeration value="frame" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="lockPhysics" type="bool" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                是否锁定物理特性,不让移动。
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateEssential">
        <xs:annotation>
            <xs:documentation>切换角色的essential状态</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateBase">
                    <xs:attribute name="essential" type="bool" use="required">
                        <xs:annotation>
                            <xs:documentation>设置角色的essential状态。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="restore" type="bool" use="required">
                        <xs:annotation>
                            <xs:documentation>当状态结束后是否恢复角色的原始essential状态.</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateAttributeDynamic">
        <xs:annotation>
            <xs:documentation>可以"持续"改变角色属性"动态值"的状态.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateBase">
                    <xs:attribute name="attributeName" type="xs:string" use="required">
                        <xs:annotation>
                            <xs:documentation>指定要改变的属性”名称“（不是id）</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:decimal" use="required">
                        <xs:annotation>
                            <xs:documentation>指定每次要改变的属性值。
                                示例，如：attrName="attributeHealth" value="10", interval="3", 则表示每3秒给角色的attributeHealth属性添加10点值。</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="interval" type="xs:decimal" use="required">
                        <xs:annotation>
                            <xs:documentation>
                                改变的时间间隔，单位秒,默认1.0秒.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateAttributeMove">
        <xs:annotation>
            <xs:documentation>
                提升角色移动速度的状态
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateAttributeBase">
                    <xs:attribute name="moveEffect" type="xs:string" use="optional">
                        <xs:annotation>
                            <xs:documentation>
                                联接一个特效．移动时的效果，只有在移动时才出现．
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stateAttribute">
        <xs:annotation>
            <xs:documentation>
                可以改变角色属性数值的状态
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="stateAttributeBase">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="stateAttributeBase">
        <xs:complexContent>
            <xs:extension base="stateBase">
                <xs:attribute name="attributeName" type="xs:string" use="required">
                    <xs:annotation><xs:documentation>属性名称（非ID)，这个名称指定了状态要改变的是哪一个属性</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="value" type="xs:decimal" use="required">
                    <xs:annotation><xs:documentation>要改变的属性数值。可正，可负</xs:documentation></xs:annotation>
                </xs:attribute>
                <xs:attribute name="restore" type="bool" use="required">
                    <xs:annotation><xs:documentation>是否在状态移除时恢复属性的原值。</xs:documentation></xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="stateBase">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="icon" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>状态图标，如：Interface/item/skill/....png,一般使用64*64图标</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="useTime" type="xs:decimal" use="required">
                    <xs:annotation>
                        <xs:documentation>状态的作用时间,单位秒,如果该值小于0，则状态将永远存在，不会退出。</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="effects" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            联接一些效果，格式："effectId1,effectId2,effectId3"，
                            角色获得状态时的效果,这些效果会在状态开始时附加在角色身上，在状态结束时停止．
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="removeOnDead" type="bool" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            当角色死亡时是否自动移除这个状态,默认false.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
</xs:schema>

=== Eftey/LuoYing/ly-core/src/data/object/state.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://fighter.huliqing.name'
    xsi:schemaLocation='http://fighter.huliqing.name meta/state.xsd'>
    
    <!-- ====================================================================-->
    <!--状态: 
    1.状态只对拥有状态的角色产生影响，不对其它目标产生作用。
    2.状态可以用来临时改变角色的各种属性值或行为
    3.状态是动态的，会有时间限制,一般在状态结束时应该恢复角色的原始状态。
    -->
    <!-- ====================================================================-->
    
    <!--测试用-->
    <stateAttribute id="stateGhostTest" icon="" useTime="30" 
                    attributes="attributeGhostRate|1,attributeDuckRate|1,attributeDefenceRate|1" 
                    dynamicApply="1" dynamicRestore="1" staticApply="1" staticRestore="1"
                    />

    <!--保护: 用于在剧情过程中保护角色别死-->
    <stateAttribute id="stateSafe" icon="Interface/skill/shield.jpg" useTime="9999" 
                    attributes="attributeDefence|99999,attributeMagicDefence|99999" 
                    dynamicApply="1" dynamicRestore="1" staticApply="1" staticRestore="1" />
    
    <!--晕眩: 让目标不能动也不能执行任何技能-->
    <stateSkillLocked id="stateStun" icon="Interface/skill/stun.png" useTime="3" 
                      lockAll="1" lockPhysics="1" lockType="reset"
                      effects="effectStateStun" />

    <!--疾风步: 增加移动速度50% -->
    <stateAttributeMove id="stateWindWalk" icon="Interface/skill/rapidWind.jpg" useTime="60" 
               attributes="attributeMoveSpeed|0.3"
               dynamicApply="1" dynamicRestore="1" staticApply="1" staticRestore="1"
               moveEffect="effectStateWindWalk" />
    
    <!--冰霜: 减速50%-->
    <stateAttribute id="stateSnowFrost" icon="Interface/skill/snow.jpg" useTime="6" 
                        attributes="attributeMoveSpeed|-0.3" 
                        dynamicApply="1" dynamicRestore="1" staticApply="1" staticRestore="1" />
    
    <!--冰冻：6秒冰冻，让角色不能动-->
    <stateSkillLocked id="stateIceFrozen" icon="Interface/skill/ysh_33.jpg" 
                      useTime="6" lockAll="1" lockPhysics="1" lockType="frame" effects="effectFrozen" />
    
    
    <!--=====================================================================-->
    <!--魔法：复活术相关状态-->
    <!--=====================================================================-->
    <!--保护角色在复活之前不被移出场景-->
    <stateEssential id="stateRebornEssential" icon="Interface/skill/essential.png" useTime="5" essential="1" restore="1" />
    <!--复活保护：让角色在刚复活的时候有几秒钟处于受保护状态-->
    <stateAttribute id="stateRebornProtect" icon="Interface/skill/shield.jpg" useTime="5" 
                    attributes="attributeDefence|99999,attributeMagicDefence|99999" 
                    dynamicApply="1" dynamicRestore="1" staticApply="1" staticRestore="1" />
    <!--增加生命值让角色复活-->
    <stateAttribute id="stateRebornAddLife" icon="" useTime="0" 
                          attributes="attributeHealth|100" 
                          dynamicApply="1" dynamicRestore="0" staticApply="0" staticRestore="0" />
    <!--让角色处于wait状态-->
    <stateSkill id="stateRebornWait" icon="" useTime="0" skillType="wait" />
    
    <!--=====================================================================-->
    <!--缠绕状态:蜘蛛的缠绕-->
    <!--=====================================================================-->
    <stateSkillLocked id="stateSpiderWeb" icon="Interface/skill/ysh_48.jpg" useTime="6"
        lockType="reset" lockSkillTypes="walk,run,jump,idle,duck,dance" lockSkillIds="skillDanceSakura,skillDualSwordWave" lockPhysics="1"
        effects="effectSpiderWeb" />
     
    <!--=====================================================================-->
    <!--狂暴状态:1分钟内提升角色的攻击速度、魔法速度、躲闪、防御、连招-->
    <!--=====================================================================-->
    <stateAttribute id="stateSpeedUpAS" icon="Interface/skill/ysh_88.jpg" useTime="60" 
                     attributes="attributeAttackSpeed|0.5,attributeMagicSpeed|0.5,attributeDefenceRate|0.5,attributeDuckRate|0.5,attributeGhostRate|0.5" 
                     dynamicApply="1" dynamicRestore="1" staticApply="1" staticRestore="1" />
    
    <!--=====================================================================-->
    <!--中毒状态:蝎子毒 -->
    <!--=====================================================================-->
    <stateAttributeDynamic id="stateScorpionVenom" icon="Interface/skill/claw.jpg" useTime="60" 
                           attributes="attributeHealth|-10" interval="3" effects="effectScorpionVenom" removeOnDead="1" />
    
    <!--=====================================================================-->
    <!--净化状态:牧师的净化技能所用，可以持续净化中毒、诅咒等-->
    <!--=====================================================================-->
    <stateClean id="stateClean" icon="Interface/skill/clean.jpg" useTime="60" states="stateScorpionVenom" />
</root>

=== Eftey/LuoYing/ly-luoying-desktop/src/data/object/state.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name ../../../../ly-kernel/src/LuoYing/Data/meta/state.xsd'>
    
    <!-- ====================================================================-->
    <!--状态: 
    1.状态只对拥有状态的角色产生影响，不对其它目标产生作用。
    2.状态可以用来临时改变角色的各种属性值或行为
    3.状态是动态的，会有时间限制,一般在状态结束时应该恢复角色的原始状态。
    -->
    <!-- ====================================================================-->
    
    <!--测试用-->
    <stateGroup id="stateGhostTest" icon="" useTime="30" states="stateGhostTest1,stateGhostTest2,stateGhostTest3" />
    <stateAttribute id="stateGhostTest1" useTime="30" attributeName="attributeGhostRate" value="1" restore="1" />
    <stateAttribute id="stateGhostTest2" useTime="30" attributeName="attributeDuckRate" value="1" restore="1" />
    <stateAttribute id="stateGhostTest2" useTime="30" attributeName="attributeDefenceRate" value="1" restore="1" />
    
    <!--保护: 用于在剧情过程中保护角色别死-->
    <stateGroup id="stateSafe" icon="Interface/skill/shield.jpg" useTime="9999" states="stateSafe1,stateSafe2" />
    <stateAttribute id="stateSafe1" useTime="9999" attributeName="attributeDefence" value="99999" restore="1" />
    <stateAttribute id="stateSafe2" useTime="9999" attributeName="attributeMagicDefence" value="99999" restore="1" />
    
    <!--晕眩: 让目标不能动也不能执行任何技能-->
    <stateSkillLocked id="stateStun" icon="Interface/skill/stun.png" useTime="3" lockAtSkillTags="reset"
                      lockAllSkillTags="1" lockLocation="1" effects="effectStateStun" />

    <!--疾风步: 增加移动速度50% -->
    <stateAttributeMove id="stateWindWalk" icon="Interface/skill/rapidWind.jpg" useTime="60"
                        attributeName="attributeMoveSpeed" value="0.3" restore="1" moveEffect="effectStateWindWalk" />
    
    <!--冰霜: 减速50%-->
    <stateAttribute id="stateSnowFrost" icon="Interface/skill/snow.jpg" useTime="6" 
                        attributeName="attributeMoveSpeed" value="-0.3" restore="1" />
    
    <!--冰冻：6秒冰冻，让角色不能动-->
    <stateSkillLocked id="stateIceFrozen" icon="Interface/skill/ysh_33.jpg" useTime="6" lockAtFrame="1" 
                      lockAllSkillTags="1" lockLocation="1" effects="effectFrozen" />
    
    <!--=====================================================================-->
    <!--魔法：复活术相关状态-->
    <!--=====================================================================-->
    <!--保护角色在复活之前不被移出场景-->
    <!--<stateEssential id="stateRebornEssential" icon="Interface/skill/essential.png" useTime="5" essential="1" restore="1" />-->
    <stateBooleanAttribute id="stateRebornEssential" icon="Interface/skill/essential.png" useTime="5" bindAttribute="attributeEssential" value="1" restore="1" />
    
    <!--复活保护：让角色在刚复活的时候有几秒钟处于受保护状态-->
    <stateGroup id="stateRebornProtect" icon="Interface/skill/shield.jpg" useTime="5" states="stateRebornProtect1,stateRebornProtect2" />
    <stateAttribute id="stateRebornProtect1" useTime="5" attributeName="attributeDefence" value="99999" restore="1" />
    <stateAttribute id="stateRebornProtect2" useTime="5" attributeName="attributeMagicDefence" value="99999" restore="1" />
    
    <!--增加生命值让角色复活-->
    <stateAttribute id="stateRebornAddLife" icon="" useTime="0" 
                          attributeName="attributeHealth" value="100" restore="0" />
    
    <!--让角色处于wait状态-->
    <stateSkill id="stateRebornWait" icon="" useTime="0" skillTags="wait" />
    
    <!--=====================================================================-->
    <!--缠绕状态:蜘蛛的缠绕-->
    <!--=====================================================================-->
    <stateSkillLocked id="stateSpiderWeb" icon="Interface/skill/ysh_48.jpg" useTime="6" lockAtSkillTags="reset"
                        lockSkillTags="walk,run,jump,idle,duck,dance" lockSkillIds="skillDanceSakura,skillDualSwordWave" 
                        lockLocation="1" effects="effectSpiderWeb" />
     
    <!--=====================================================================-->
    <!--狂暴状态:1分钟内提升角色的攻击速度、魔法速度、躲闪、防御、连招-->
    <!--=====================================================================-->
    <stateGroup id="stateSpeedUpAS" icon="Interface/skill/ysh_88.jpg" useTime="60" 
                states="stateSpeedUpAS1,stateSpeedUpAS2,stateSpeedUpAS3,stateSpeedUpAS4,stateSpeedUpAS5" />
    <stateAttribute id="stateSpeedUpAS1" useTime="60" attributeName="attributeAttackSpeed" value="0.5" restore="1" />
    <stateAttribute id="stateSpeedUpAS2" useTime="60" attributeName="attributeMagicSpeed" value="0.5" restore="1" />
    <stateAttribute id="stateSpeedUpAS3" useTime="60" attributeName="attributeDefenceRate" value="0.5" restore="1" />
    <stateAttribute id="stateSpeedUpAS4" useTime="60" attributeName="attributeDuckRate" value="0.5" restore="1" />
    <stateAttribute id="stateSpeedUpAS5" useTime="60" attributeName="attributeGhostRate" value="0.5" restore="1" />
    
    <!--=====================================================================-->
    <!--中毒状态:蝎子毒 -->
    <!--=====================================================================-->
    <stateAttributeDynamic id="stateScorpionVenom" icon="Interface/skill/claw.jpg" useTime="30" attributeName="attributeHealth" 
                           value="-10" interval="3" effects="effectScorpionVenom" removeOnDead="1" bindDeadAttribute="attributeDead" />
    
    <!--=====================================================================-->
    <!--净化状态:牧师的净化技能所用，可以持续净化中毒、诅咒等-->
    <!--=====================================================================-->
    <stateClean id="stateClean" icon="Interface/skill/clean.jpg" useTime="60" states="stateScorpionVenom" />
</root>
