=== Eftey/LuoYing/ly-core/src/data/object/meta/handler.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fighter.huliqing.name"
           xmlns="http://fighter.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:include schemaLocation="base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="handlerTest" />
                <xs:element ref="handlerAttribute" />
                <xs:element ref="handlerSummon" />
                <!--remove20160406,use handlerItemSkill instead-->
                <!--<xs:element ref="handlerSummonSkill" />-->
                <xs:element ref="handlerOutfit" />
                <xs:element ref="handlerWeapon" />
                <xs:element ref="handlerSkill" />
                <xs:element ref="handlerSkillBook" />
                <xs:element ref="handlerStateGain" />
                <xs:element ref="handlerStateRemove" />
                <xs:element ref="handlerItemSkill" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerItemSkill">
        <xs:annotation><xs:documentation>使用物品，这个物品会使用一个技能。</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase">
                    <xs:attribute name="skill" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>默认要使用的技能</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="special" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>
                                格式："race|sex|skill,race|sex|skill,...", 指定根据“种族”、“性别”来确定要使用哪一个技能.
                                比如在某些情况下，不同的种族及角色性别可能要使用不同的动作技能。
                                当找不到可匹配的技能时，将使用默认的技能。sex使用 "f","m"代替，如：
                                "1|f|attack1" 即表示当人族女性使用物品时将执行技能attack1
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerStateRemove">
        <xs:annotation><xs:documentation>获取状态</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase">
                    <xs:attribute name="states" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>要移除的状态列表，格式如："stateId,stateId,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerStateGain">
        <xs:annotation><xs:documentation>获取状态</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase">
                    <xs:attribute name="states" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要获得的状态列表，格式如："stateId,stateId,..."</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerSkillBook">
        <xs:annotation><xs:documentation>技能书,用于学习指定的技能</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase">
                    <xs:attribute name="skill" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要学习的技能ID</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
<!--    <xs:element name="handlerSummonSkill">
        <xs:annotation><xs:documentation>召唤角色,但是要求角色需要有召唤技能</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase">
                    <xs:attribute name="actorId" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要召唤的角色ID</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="skillId" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>需要依赖的召唤技能，该参数绑定一个召唤技能</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>-->

    <xs:element name="handlerSummon">
        <xs:annotation><xs:documentation>召唤角色</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase">
                    <xs:attribute name="actorId" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                指定要召唤的角色ID
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="total" type="xs:integer" use="required" >
                        <xs:annotation>
                            <xs:documentation>
                                指定要召唤多少个角色
                            </xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerSkill">
        <xs:annotation><xs:documentation>技能执行</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase"></xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerWeapon">
        <xs:annotation><xs:documentation>切换武器</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase" />
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerOutfit">
        <xs:annotation><xs:documentation>切换装备</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase" />
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerAttribute" >
        <xs:annotation>
            <xs:documentation>操作属性值</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="handlerBase">
                    <xs:attribute name="attribute" type="xs:integer" use="required" >
                        <xs:annotation><xs:documentation>指定要操作的是哪一个属性ID</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="amount" type="xs:decimal" use="required" >
                        <xs:annotation><xs:documentation>指定补多少量,可正可负，正表示增加，负表示减少</xs:documentation></xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="handlerTest" >
        <xs:annotation><xs:documentation>测试用</xs:documentation></xs:annotation>
        <xs:complexType>
            <xs:complexContent><xs:extension base="handlerBase" /></xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="handlerBase">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="effects" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                        效果,格式: "effect1,effect2,...",
                        这些效果会在handler执行时立即应用在角色身上。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="sounds" type="xs:string" use="optional" >
                    <xs:annotation>
                        <xs:documentation>
                        声效,格式: "sound1,sound2,...",
                        这些声音会在handler执行时立即播放,在角色的目标位置。
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== Eftey/LuoYing/ly-core/src/data/object/handler.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://fighter.huliqing.name'
    xsi:schemaLocation='http://fighter.huliqing.name meta/handler.xsd'>
    
    <!--测试用-->
    <handlerTest id="handlerTest" />
    
    <!-- ========================================================================= -->
    
    <!--召唤防御塔－火-->
    <handlerSummon id="handlerSummonTower" actorId="actorTower" total="1" />
    <!--召唤防御塔-石-->
    <handlerSummon id="handlerSummonTowerStone" actorId="actorTowerStone" total="1" />
    <!--召唤防御塔-冰-->
    <handlerSummon id="handlerSummonTowerSnow" actorId="actorTowerSnow" total="1" />
    
    <!-- ========================================================================= -->
    
    <!--<handlerSummonSkill id="handlerSummonSpider" actorId="actorSpiderMin" skillId="skillSummon" />-->
    <!--<handlerSummonSkill id="handlerSummonWolf" actorId="actorWolf" skillId="skillSummon" />-->
    <!--<handlerSummonSkill id="handlerSummonBear" actorId="actorBear" skillId="skillSummon" />-->
    <!--<handlerSummonSkill id="handlerSummonScorpion" actorId="actorScorpion" skillId="skillSummon" />-->
    <!--<handlerSummonSkill id="handlerSummonGb" actorId="actorGbSmall" skillId="skillSummon" />-->
    <!--召唤蜘蛛-->
    <handlerItemSkill id="handlerSummonSpider" skill="skillSummonSpider" />
    <!--召唤狼-->
    <handlerItemSkill id="handlerSummonWolf" skill="skillSummonWolf" />
    <!--召唤熊-->
    <handlerItemSkill id="handlerSummonBear" skill="skillSummonBear" />
    <!--召唤蝎子-->
    <handlerItemSkill id="handlerSummonScorpion" skill="skillSummonScorpion" />
    <!--召唤古柏子孙-->
    <handlerItemSkill id="handlerSummonGb" skill="skillSummonGb" />
    <!--召唤迅猛龙raptor-->
    <handlerItemSkill id="handlerSummonRaptor" skill="skillSummonRaptor" />
    <!--召唤雷克斯-->
    <handlerItemSkill id="handlerSummonTrex" skill="skillSummonTrex" />
    
    <!-- ========================================================================= -->

    <!-- 补血补魔 -->
    <handlerAttribute id="handlerTonicHealth" attribute="attributeHealth" amount="200" effects="effectRandomFire" />
    <handlerAttribute id="handlerTonicMagic" attribute="attributeMana" amount="200" effects="effectRandomFire" />
    
    <!-- ========================================================================= -->
    
    <!-- 换装 -->
    <handlerOutfit id="handlerOutfit" sounds="soundDressOutfit" />
    
    <!-- ========================================================================= -->
    
    <!-- 换武器 -->
    <handlerWeapon id="handlerWeaponSword" sounds="soundDrawSword" />
    <handlerWeapon id="handlerWeaponBow" sounds="soundDrawBow" />
    <handlerWeapon id="handlerWeaponWand" sounds="soundDressOutfit2" />
    
    <!-- ========================================================================= -->
    
    <!-- 执行技能 -->
    <handlerSkill id="handlerSkill" />
    
    <!-- ========================================================================= -->
    
    <!--技能书基本配置-->
    <handlerSkillBook id="handlerSkillBookBase" effects="effectLearnSkill" />
    <!--学习野兽召唤-->
    <handlerSkillBook id="handlerSkillBookSummon"  extends="handlerSkillBookBase"  skill="skillSummon" />
    <!--学习闪电箭-->
    <handlerSkillBook id="handlerSkillBookLightningShot" extends="handlerSkillBookBase"  skill="skillLightningShot" />
    <!--学习传送术-->
    <handlerSkillBook id="handlerSkillBookBack" extends="handlerSkillBookBase"  skill="skillBack" />
    <!--学习落樱飞舞-->
    <handlerSkillBook id="handlerSkillBookDanceSakura" extends="handlerSkillBookBase"  skill="skillDanceSakura" />
    <!--学习寒冰箭-->
    <handlerSkillBook id="handlerSkillBookIceShot" extends="handlerSkillBookBase"  skill="skillIceShot" />
    <!--学习二刀流冲击波-->
    <handlerSkillBook id="handlerSkillBookDualSwordWave" extends="handlerSkillBookBase" skill="skillDualSwordWave" />

    <!-- ========================================================================= -->
    <!--复活-->
    <handlerItemSkill id="handlerItemReborn" skill="skillShotReborn" />
    
    <!-- ========================================================================= -->
    <!--获得状态、解除状态-->
    <!-- ========================================================================= -->

    <!--获得“疾风步”的状态-->
    <handlerStateGain id="handlerStateGainWindWalk" states="stateWindWalk" effects="effectRandomFire" />
    <!--获得“狂暴”状态-->
    <handlerStateGain id="handlerStateGainAS" states="stateSpeedUpAS" effects="effectRandomFire" />
    
    <!--解除中毒状态: 解毒草用-->
    <handlerStateRemove id="handlerStateRemoveScorpionVenom" states="stateScorpionVenom" effects="effectTonic" />
    
    <!-- ========================================================================= -->
    <!--地图数据-->
    <!-- ========================================================================= -->
    <handlerMap id="handlerWorldMap" image="Interface/map/map.jpg" 
                locations="
  StoryTreasure|0.2|0.2|gameStoryTreasure
, StoryGb|0.3|0.3|gameStoryGb
, StoryGuard|0.4|0.4|gameStoryGuard
, Survival|0.5|0.5|gameSurvival" />
    
</root>
